//! Roc Platform ABI
//!
//! This file defines the Zig interface for hosted functions in a Roc platform.
//! It is automatically generated by the Roc glue generator.
//!
//! Usage:
//! 1. Import this file in your platform host
//! 2. Implement each hosted function according to its signature
//! 3. Call hostedFunctions() to create the dispatch table for RocOps

const std = @import("std");

/// Type-erased function pointer for hosted function dispatch.
pub const HostedFn = *const fn (*anyopaque, *anyopaque, *anyopaque) callconv(.c) void;

/// Table of hosted function pointers passed to the Roc runtime.
pub const HostedFunctions = extern struct {
    count: u32,
    fns: [*]HostedFn,
};

/// Arguments for a Roc allocation request.
pub const RocAlloc = extern struct { alignment: usize, length: usize, answer: *anyopaque };
/// Arguments for a Roc deallocation request.
pub const RocDealloc = extern struct { alignment: usize, ptr: *anyopaque };
/// Arguments for a Roc reallocation request.
pub const RocRealloc = extern struct { alignment: usize, new_length: usize, answer: *anyopaque };
/// Arguments for a Roc `dbg` expression.
pub const RocDbg = extern struct { utf8_bytes: [*]u8, len: usize };
/// Arguments for a failed Roc `expect`.
pub const RocExpectFailed = extern struct { utf8_bytes: [*]u8, len: usize };
/// Arguments for a Roc `crash`.
pub const RocCrashed = extern struct { utf8_bytes: [*]u8, len: usize };

/// The operations table passed from the host to the Roc runtime.
pub const RocOps = extern struct {
    env: *anyopaque,
    roc_alloc: *const fn (*RocAlloc, *anyopaque) callconv(.c) void,
    roc_dealloc: *const fn (*RocDealloc, *anyopaque) callconv(.c) void,
    roc_realloc: *const fn (*RocRealloc, *anyopaque) callconv(.c) void,
    roc_dbg: *const fn (*const RocDbg, *anyopaque) callconv(.c) void,
    roc_expect_failed: *const fn (*const RocExpectFailed, *anyopaque) callconv(.c) void,
    roc_crashed: *const fn (*const RocCrashed, *anyopaque) callconv(.c) void,
    hosted_fns: HostedFunctions,
};

/// Type-erase a hosted function pointer to `HostedFn`.
///
/// Hosted functions are typically written with concrete parameter types for clarity
/// (e.g. `*RocOps`, `*RocStr`, `[*]u8`), but must be stored as `HostedFn` which
/// uses `*anyopaque` for all parameters. This helper performs that cast.
pub fn hostedFn(func: anytype) HostedFn {
    const T = @TypeOf(func);
    const info = @typeInfo(T);
    if (info == .pointer) {
        const child = @typeInfo(info.pointer.child);
        if (child == .@"fn") {
            const f = child.@"fn";
            if (f.params.len != 3)
                @compileError("hostedFn: function must take exactly 3 parameters (ops, ret_ptr, args_ptr)");
            if (f.return_type != void)
                @compileError("hostedFn: function must return void");
        }
    }
    return @ptrCast(func);
}

/// A Roc string value. Small strings (up to 23 bytes) are stored inline;
/// larger strings are heap-allocated with a reference count.
pub const RocStr = extern struct {
    bytes: ?[*]u8,
    length: usize,
    capacity_or_alloc_ptr: usize,

    const Self = @This();
    const small_string_size = @sizeOf(RocStr);
    const small_str_max_length = small_string_size - 1;
    const seamless_slice_bit: usize = @as(usize, @bitCast(@as(isize, std.math.minInt(isize))));

    /// Return the string contents as a `[]const u8` slice.
    pub fn asSlice(self: *const Self) []const u8 {
        return self.asU8ptr()[0..self.len()];
    }

    /// Return the length of the string in bytes.
    pub fn len(self: Self) usize {
        if (self.isSmallStr()) {
            return @as([*]const u8, @ptrCast(&self))[@sizeOf(Self) - 1] ^ 0b1000_0000;
        } else {
            return self.length & ~seamless_slice_bit;
        }
    }

    /// Return true if the string has zero length.
    pub fn isEmpty(self: Self) bool {
        return self.len() == 0;
    }

    /// Return true if this string is stored inline (small string optimization).
    pub fn isSmallStr(self: Self) bool {
        return @as(isize, @bitCast(self.capacity_or_alloc_ptr)) < 0;
    }

    /// Return true if this string is a seamless slice into another allocation.
    pub fn isSeamlessSlice(self: Self) bool {
        return !self.isSmallStr() and @as(isize, @bitCast(self.length)) < 0;
    }

    /// Return a pointer to the raw UTF-8 bytes.
    pub fn asU8ptr(self: *const Self) [*]const u8 {
        if (self.isSmallStr()) {
            return @as([*]const u8, @ptrCast(self));
        } else {
            return @as([*]const u8, @ptrCast(self.bytes));
        }
    }

    /// Return an empty RocStr.
    pub fn empty() Self {
        return .{ .bytes = null, .length = 0, .capacity_or_alloc_ptr = seamless_slice_bit };
    }

    /// Create a RocStr from a byte slice, using `roc_ops` for heap allocation if needed.
    pub fn fromSlice(slice: []const u8, roc_ops: *RocOps) Self {
        if (slice.len < small_string_size) {
            var result = Self.empty();
            const ptr: [*]u8 = @ptrCast(&result);
            @memcpy(ptr[0..slice.len], slice);
            ptr[@sizeOf(Self) - 1] = @as(u8, @intCast(slice.len)) | 0b1000_0000;
            return result;
        } else {
            const ptr_width = @sizeOf(usize);
            const extra_bytes = ptr_width;
            const total = extra_bytes + slice.len;
            var alloc_args: RocAlloc = .{
                .alignment = @alignOf(usize),
                .length = total,
                .answer = undefined,
            };
            roc_ops.roc_alloc(&alloc_args, roc_ops.env);
            const base: [*]u8 = @ptrCast(alloc_args.answer);
            const data_ptr = base + extra_bytes;
            const rc: *isize = @ptrFromInt(@intFromPtr(data_ptr) - @sizeOf(isize));
            rc.* = 1;
            @memcpy(data_ptr[0..slice.len], slice.ptr[0..slice.len]);
            return .{
                .bytes = data_ptr,
                .length = slice.len,
                .capacity_or_alloc_ptr = slice.len,
            };
        }
    }

    /// Decrement the reference count; frees the allocation when it reaches zero.
    pub fn decref(self: Self, roc_ops: *RocOps) void {
        if (self.isSmallStr()) return;
        const alloc_ptr = self.getAllocationPtr() orelse return;
        const data_addr = @intFromPtr(alloc_ptr);
        const rc: *isize = @ptrFromInt(data_addr - @sizeOf(isize));
        const prev = @atomicRmw(isize, rc, .Sub, 1, .monotonic);
        if (prev == 1) {
            const ptr_width = @sizeOf(usize);
            const base: *anyopaque = @ptrFromInt(data_addr - ptr_width);
            var dealloc_args: RocDealloc = .{ .alignment = @alignOf(usize), .ptr = base };
            roc_ops.roc_dealloc(&dealloc_args, roc_ops.env);
        }
    }

    /// Increment the reference count by `amount`.
    pub fn incref(self: Self, amount: isize) void {
        if (self.isSmallStr()) return;
        const alloc_ptr = self.getAllocationPtr() orelse return;
        const rc: *isize = @ptrFromInt(@intFromPtr(alloc_ptr) - @sizeOf(isize));
        _ = @atomicRmw(isize, rc, .Add, amount, .monotonic);
    }

    /// Return true if this string has a reference count of exactly one.
    pub fn isUnique(self: Self) bool {
        if (self.isSmallStr()) return true;
        if (self.capacity_or_alloc_ptr == 0) return true;
        const alloc_ptr = self.getAllocationPtr() orelse return true;
        const rc: *const isize = @ptrFromInt(@intFromPtr(alloc_ptr) - @sizeOf(isize));
        return rc.* == 1;
    }

    fn getAllocationPtr(self: Self) ?[*]u8 {
        if (self.isSeamlessSlice()) {
            return @as(?[*]u8, @ptrFromInt(self.capacity_or_alloc_ptr << 1));
        } else {
            return self.bytes;
        }
    }
};

/// A generic Roc list. Elements are reference-counted and heap-allocated.
///
/// When `elements_refcounted` is true (the default), an extra `ptr_width` bytes
/// are reserved in the allocation header for the element count, matching the Roc
/// runtime's `allocateWithRefcount` layout. Set to `false` for lists of
/// non-refcounted primitives (e.g. `U8`, `I32`).
pub fn RocList(comptime T: type) type {
    return RocListWith(T, true);
}

/// Parameterized list constructor; use `RocList(T)` for refcounted elements.
pub fn RocListWith(comptime T: type, comptime elements_refcounted: bool) type {
    return extern struct {
        elements_ptr: ?[*]T,
        length: usize,
        capacity_or_alloc_ptr: usize,

        const Self = @This();
        const ptr_width = @sizeOf(usize);
        const required_space: usize = if (elements_refcounted) (2 * ptr_width) else ptr_width;
        const header_bytes = @max(required_space, @alignOf(T));
        const alloc_align = @max(ptr_width, @alignOf(T));

        /// Return the list elements as a `[]const T` slice.
        pub fn items(self: Self) []const T {
            if (self.elements_ptr) |ptr| return ptr[0..self.length];
            return &[_]T{};
        }

        /// Return the number of elements in the list.
        pub fn len(self: Self) usize {
            return self.length;
        }

        /// Return true if the list has zero elements.
        pub fn isEmpty(self: Self) bool {
            return self.length == 0;
        }

        /// Return an empty RocList.
        pub fn empty() Self {
            return .{ .elements_ptr = null, .length = 0, .capacity_or_alloc_ptr = 0 };
        }

        /// Allocate a new list with space for `length` elements.
        pub fn allocate(length: usize, roc_ops: *RocOps) Self {
            if (length == 0) return empty();
            const data_bytes = length * @sizeOf(T);
            const total = data_bytes + header_bytes;
            var alloc_args: RocAlloc = .{
                .alignment = alloc_align,
                .length = total,
                .answer = undefined,
            };
            roc_ops.roc_alloc(&alloc_args, roc_ops.env);
            const base: [*]u8 = @ptrCast(alloc_args.answer);
            const data_ptr = base + header_bytes;
            const rc: *isize = @ptrFromInt(@intFromPtr(data_ptr) - @sizeOf(isize));
            rc.* = 1;
            return .{
                .elements_ptr = @ptrCast(@alignCast(data_ptr)),
                .length = length,
                .capacity_or_alloc_ptr = length,
            };
        }

        /// Create a RocList from a slice, copying elements into a new allocation.
        pub fn fromSlice(slice: []const T, roc_ops: *RocOps) Self {
            if (slice.len == 0) return empty();
            const list = allocate(slice.len, roc_ops);
            const dest: [*]u8 = @ptrCast(list.elements_ptr.?);
            const src: [*]const u8 = @ptrCast(slice.ptr);
            @memcpy(dest[0 .. slice.len * @sizeOf(T)], src[0 .. slice.len * @sizeOf(T)]);
            return list;
        }

        /// Decrement the reference count; frees the allocation when it reaches zero.
        pub fn decref(self: Self, roc_ops: *RocOps) void {
            const ptr = self.elements_ptr orelse return;
            const data_addr = @intFromPtr(ptr);
            const rc: *isize = @ptrFromInt(data_addr - @sizeOf(isize));
            const prev = @atomicRmw(isize, rc, .Sub, 1, .monotonic);
            if (prev == 1) {
                const base: *anyopaque = @ptrFromInt(data_addr - header_bytes);
                var dealloc_args: RocDealloc = .{
                    .alignment = alloc_align,
                    .ptr = base,
                };
                roc_ops.roc_dealloc(&dealloc_args, roc_ops.env);
            }
        }

        /// Increment the reference count by `amount`.
        pub fn incref(self: Self, amount: isize) void {
            const ptr = self.elements_ptr orelse return;
            const rc: *isize = @ptrFromInt(@intFromPtr(ptr) - @sizeOf(isize));
            _ = @atomicRmw(isize, rc, .Add, amount, .monotonic);
        }

        /// Return true if this list has a reference count of exactly one.
        pub fn isUnique(self: Self) bool {
            const ptr = self.elements_ptr orelse return true;
            if (self.capacity_or_alloc_ptr == 0) return true;
            const rc: *const isize = @ptrFromInt(@intFromPtr(ptr) - @sizeOf(isize));
            return rc.* == 1;
        }
    };
}

/// Tag discriminant for Try.
pub const TryTag = enum(u8) {
    Err = 0,
    Ok = 1,
};

/// Tag union: Try
pub const Try = extern struct {
    payload: extern union {
        err: i32,
        ok: void,
    },
    tag: TryTag,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(Try) != 8) @compileError("Try size mismatch");
        if (@alignOf(Try) != 4) @compileError("Try alignment mismatch");
    }
}

/// Arguments for Stderr.line!
/// Roc signature: Str => {}
pub const StderrLineArgs = extern struct {
    arg0: RocStr,
};

/// Arguments for Stdout.line!
/// Roc signature: Str => {}
pub const StdoutLineArgs = extern struct {
    arg0: RocStr,
};

/// Implement this struct with your hosted function implementations.
/// Pass it to hostedFunctions() to create the dispatch table.
pub const PlatformHostedFns = struct {
    stderr_line: *const fn (*RocOps, *anyopaque, *const StderrLineArgs) callconv(.c) void, // Stderr.line!
    stdin_line: *const fn (*RocOps, *RocStr, *anyopaque) callconv(.c) void, // Stdin.line!
    stdout_line: *const fn (*RocOps, *anyopaque, *const StdoutLineArgs) callconv(.c) void, // Stdout.line!
};

/// Create a HostedFunctions dispatch table from your implementations.
/// The comptime parameter + nested struct ensures the function pointer array
/// lives in static memory, not on the stack.
pub fn hostedFunctions(comptime fns: PlatformHostedFns) HostedFunctions {
    const Static = struct {
        const ptrs = [_]HostedFn{
            hostedFn(fns.stderr_line), // Stderr.line! (index 0)
            hostedFn(fns.stdin_line), // Stdin.line! (index 1)
            hostedFn(fns.stdout_line), // Stdout.line! (index 2)
        };
    };
    return .{
        .count = Static.ptrs.len,
        .fns = @constCast(&Static.ptrs),
    };
}

/// Default memory management functions for Roc platforms.
///
/// Returns a struct with `rocAlloc`, `rocDealloc`, and `rocRealloc` functions
/// that follow the Roc ABI and use `EnvType.allocator()` for allocation.
///
/// Memory layout: each allocation prepends size metadata so that dealloc/realloc
/// can recover the original allocation size (required because `roc_dealloc` does
/// not receive a length parameter).
///
/// `EnvType` must have an `.allocator()` method that returns `std.mem.Allocator`.
pub fn DefaultAllocators(comptime EnvType: type) type {
    return struct {
        /// Allocate memory for the Roc runtime using the host environment's allocator.
        pub fn rocAlloc(alloc_args: *RocAlloc, env_ptr: *anyopaque) callconv(.c) void {
            const host_env: *EnvType = @ptrCast(@alignCast(env_ptr));
            const allocator = host_env.allocator();

            const min_alignment: usize = @max(alloc_args.alignment, @alignOf(usize));
            const align_enum = std.mem.Alignment.fromByteUnits(min_alignment);
            const size_storage_bytes = min_alignment;
            const total_size = alloc_args.length + size_storage_bytes;

            const base_ptr = allocator.rawAlloc(total_size, align_enum, @returnAddress()) orelse {
                const stderr_file: std.fs.File = .stderr();
                stderr_file.writeAll("roc_alloc: out of memory\n") catch {};
                std.process.exit(1);
            };

            // Store total size immediately before the user data pointer
            const size_ptr: *usize = @ptrFromInt(@intFromPtr(base_ptr) + size_storage_bytes - @sizeOf(usize));
            size_ptr.* = total_size;

            alloc_args.answer = @ptrFromInt(@intFromPtr(base_ptr) + size_storage_bytes);
        }

        /// Free memory previously allocated by `rocAlloc`.
        pub fn rocDealloc(dealloc_args: *RocDealloc, env_ptr: *anyopaque) callconv(.c) void {
            const host_env: *EnvType = @ptrCast(@alignCast(env_ptr));
            const allocator = host_env.allocator();

            const min_alignment: usize = @max(dealloc_args.alignment, @alignOf(usize));
            const align_enum = std.mem.Alignment.fromByteUnits(min_alignment);
            const size_storage_bytes = min_alignment;

            const size_ptr: *const usize = @ptrFromInt(@intFromPtr(dealloc_args.ptr) - @sizeOf(usize));
            const total_size = size_ptr.*;

            const base_ptr: [*]u8 = @ptrFromInt(@intFromPtr(dealloc_args.ptr) - size_storage_bytes);
            const slice = base_ptr[0..total_size];
            allocator.rawFree(slice, align_enum, @returnAddress());
        }

        /// Reallocate memory, copying existing data to the new allocation.
        pub fn rocRealloc(realloc_args: *RocRealloc, env_ptr: *anyopaque) callconv(.c) void {
            const host_env: *EnvType = @ptrCast(@alignCast(env_ptr));
            const allocator = host_env.allocator();

            const min_alignment: usize = @max(realloc_args.alignment, @alignOf(usize));
            const align_enum = std.mem.Alignment.fromByteUnits(min_alignment);
            const size_storage_bytes = min_alignment;

            // Read old size from metadata
            const old_size_ptr: *const usize = @ptrFromInt(@intFromPtr(realloc_args.answer) - @sizeOf(usize));
            const old_total_size = old_size_ptr.*;
            const old_base_ptr: [*]u8 = @ptrFromInt(@intFromPtr(realloc_args.answer) - size_storage_bytes);

            // Allocate new block
            const new_total_size = realloc_args.new_length + size_storage_bytes;
            const new_base_ptr = allocator.rawAlloc(new_total_size, align_enum, @returnAddress()) orelse {
                const stderr_file: std.fs.File = .stderr();
                stderr_file.writeAll("roc_realloc: out of memory\n") catch {};
                std.process.exit(1);
            };

            // Copy old user data to new location
            const old_user_data_size = old_total_size - size_storage_bytes;
            const copy_size = @min(old_user_data_size, realloc_args.new_length);
            const new_user_ptr: [*]u8 = @ptrFromInt(@intFromPtr(new_base_ptr) + size_storage_bytes);
            const old_user_ptr: [*]const u8 = @ptrCast(realloc_args.answer);
            @memcpy(new_user_ptr[0..copy_size], old_user_ptr[0..copy_size]);

            // Free old allocation
            allocator.rawFree(old_base_ptr[0..old_total_size], align_enum, @returnAddress());

            // Store new size and return user pointer
            const new_size_ptr: *usize = @ptrFromInt(@intFromPtr(new_base_ptr) + size_storage_bytes - @sizeOf(usize));
            new_size_ptr.* = new_total_size;
            realloc_args.answer = new_user_ptr;
        }
    };
}

/// Default handlers for dbg, expect-failed, and crash.
///
/// These print to stderr and don't use the env pointer. Suitable for most
/// platform hosts that don't need custom handling of these events.
pub const DefaultHandlers = struct {
    /// Print a `dbg` expression to stderr.
    pub fn rocDbg(dbg_args: *const RocDbg, _: *anyopaque) callconv(.c) void {
        const msg = dbg_args.utf8_bytes[0..dbg_args.len];
        const stderr_file: std.fs.File = .stderr();
        stderr_file.writeAll("\x1b[36m[ROC DBG]\x1b[0m ") catch {};
        stderr_file.writeAll(msg) catch {};
        stderr_file.writeAll("\n") catch {};
    }

    /// Print a failed `expect` to stderr.
    pub fn rocExpectFailed(expect_args: *const RocExpectFailed, _: *anyopaque) callconv(.c) void {
        const msg = expect_args.utf8_bytes[0..expect_args.len];
        const stderr_file: std.fs.File = .stderr();
        stderr_file.writeAll("\x1b[33m[ROC EXPECT]\x1b[0m ") catch {};
        stderr_file.writeAll(msg) catch {};
        stderr_file.writeAll("\n") catch {};
    }

    /// Print a `crash` message to stderr and exit.
    pub fn rocCrashed(crash_args: *const RocCrashed, _: *anyopaque) callconv(.c) void {
        const msg = crash_args.utf8_bytes[0..crash_args.len];
        const stderr_file: std.fs.File = .stderr();
        stderr_file.writeAll("\x1b[31m[ROC CRASHED]\x1b[0m ") catch {};
        stderr_file.writeAll(msg) catch {};
        stderr_file.writeAll("\n") catch {};
        std.process.exit(1);
    }
};

/// Create a RocOps struct with default memory management and error handlers.
///
/// This is a convenience function that wires together `DefaultAllocators(EnvType)`,
/// `DefaultHandlers`, and the provided hosted functions into a ready-to-use `RocOps`.
///
/// `EnvType` must have an `.allocator()` method that returns `std.mem.Allocator`.
///
/// Example usage:
/// ```
/// var roc_ops = makeRocOps(HostEnv, &host_env, hostedFunctions(.{ ... }));
/// ```
pub fn makeRocOps(comptime EnvType: type, env: *EnvType, hosted_fns: HostedFunctions) RocOps {
    const Allocs = DefaultAllocators(EnvType);
    return .{
        .env = @ptrCast(env),
        .roc_alloc = &Allocs.rocAlloc,
        .roc_dealloc = &Allocs.rocDealloc,
        .roc_realloc = &Allocs.rocRealloc,
        .roc_dbg = &DefaultHandlers.rocDbg,
        .roc_expect_failed = &DefaultHandlers.rocExpectFailed,
        .roc_crashed = &DefaultHandlers.rocCrashed,
        .hosted_fns = hosted_fns,
    };
}

// =============================================================================
// Entrypoint Declarations
//
// Extern declarations for Roc entrypoints. Call these from your platform host
// to invoke Roc application functions.
// =============================================================================

/// Entrypoint: main_for_host!
pub extern fn roc__main_for_host(ops: *RocOps, ret_ptr: *i32, arg_ptr: ?*const RocList(RocStr)) callconv(.c) void;

