on:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test-native:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - operating-system: ubuntu-20.04
            roc-archive: roc_nightly-linux_x86_64-latest.tar.gz
            package-manager: apt
          - operating-system: ubuntu-22.04
            roc-archive: roc_nightly-linux_x86_64-latest.tar.gz
            package-manager: apt
          - operating-system: macos-13
            roc-archive: roc_nightly-macos_apple_silicon-latest.tar.gz
            package-manager: brew
          - operating-system: macos-14
            roc-archive: roc_nightly-macos_apple_silicon-latest.tar.gz
            package-manager: brew
    steps:
      - uses: actions/checkout@v3
      - uses: korandoru/setup-zig@v1
        with:
          zig-version: 0.11.0

      - name: fetch latest release
        run: curl -fOL https://github.com/roc-lang/roc/releases/download/nightly/${{ matrix.roc-archive }}

      - name: rename nightly tar
        run: mv $(ls | grep "roc_nightly.*tar\.gz") roc_nightly.tar.gz

      - name: decompress the tar
        run: tar -xzf roc_nightly.tar.gz

      - name: remove tar
        run: rm roc_nightly.tar.gz

      - name: simplify nightly folder name
        run: mv roc_nightly* roc_nightly

      - name: check roc version
        run: ./roc_nightly/roc version

      - name: install expect for testing (Linux)
        if: runner.os == 'Linux'
        run: sudo apt install -y expect

      - name: install expect for testing (macOS)
        if: runner.os == 'macOS'
        run: brew install expect

      - name: check expect version
        run: expect -v

      - name: Build the platform
        run: ./roc_nightly/roc build.roc

      - name: Run all tests
        run: ROC=./roc_nightly/roc EXAMPLES_DIR=./examples/ ./ci/all_tests.sh
