on:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test-native:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - operating-system: ubuntu-20.04
            package-manager: apt
          - operating-system: ubuntu-22.04
            package-manager: apt
          - operating-system: macos-13
            package-manager: brew
          - operating-system: macos-14
            package-manager: brew
    steps:
      - uses: actions/checkout@v3
      - uses: korandoru/setup-zig@v1
        with:
          zig-version: 0.13.0

      - name: Install Roc
        uses: hasnep/setup-roc@main
        with:
          roc-version: nightly
          testing: auto

      - name: install expect for testing (Linux)
        if: runner.os == 'Linux'
        run: sudo apt install -y expect

      - name: install expect for testing (macOS)
        if: runner.os == 'macOS'
        run: brew install expect

      - name: check the roc version
        run: roc --version

      - name: check zig version
        run: zig version

      - name: check expect version
        run: expect -v

      - name: show current directory
        run: |
          pwd
          ls -la

      - name: build the platform
        run: roc build.roc

      - name: run the tests
        run: ROC=roc EXAMPLES_DIR=./examples/ ./ci/all_tests.sh
